<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.objectmodel.core="http:///orgomg/cwm/objectmodel/core.ecore" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_OzIG8HNZEeuOLcAiuBiIdw" name="LocalMysql_Lotus" supplierDependency="_OzIG_XNZEeuOLcAiuBiIdw" id="_JJnvgHNTEeuOLcAiuBiIdw" label="LocalMysql_Lotus" dataPackage="_OzIG_nNZEeuOLcAiuBiIdw" DatabaseType="MySQL" DriverClass="com.mysql.cj.jdbc.Driver" URL="jdbc:mysql://localhost:3306/lotus?noDatetimeStringSync=true" dbVersionString="MYSQL_8" Port="3306" Username="root" Password="enc:system.encryption.key.v1:VqSpDdVqwN+NTngaUNb5zA7/Q3bCr+6ft6k2Wv+0rzzRAXs=" ServerName="localhost" DatasourceName="" FileFieldName="" SID="lotus" SqlSynthax="" StringQuote="" NullChar="" DbmsId="mysql_id" ProductId="MYSQL" AdditionalParams="noDatetimeStringSync=true" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_OzIG8XNZEeuOLcAiuBiIdw" tag="Is Conn Need Reload" value="false"/>
    <taggedValue xmi:id="_OzIG8nNZEeuOLcAiuBiIdw" tag="package filter" value=""/>
    <taggedValue xmi:id="_OzIG83NZEeuOLcAiuBiIdw" tag="Status" value=""/>
    <taggedValue xmi:id="_OzIG9HNZEeuOLcAiuBiIdw" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_OzIG9XNZEeuOLcAiuBiIdw" tag="Purpose" value=""/>
    <taggedValue xmi:id="_OzIG9nNZEeuOLcAiuBiIdw" tag="Description" value=""/>
    <taggedValue xmi:id="_OzIG93NZEeuOLcAiuBiIdw" tag="Author" value=""/>
    <taggedValue xmi:id="_OzIG-HNZEeuOLcAiuBiIdw" tag="otherParameter"/>
    <taggedValue xmi:id="_OzIG-XNZEeuOLcAiuBiIdw" tag="DB ProductName" value="MySQL"/>
    <taggedValue xmi:id="_OzIG-nNZEeuOLcAiuBiIdw" tag="DB ProductVersion" value="8.0.16"/>
    <taggedValue xmi:id="_OzIG-3NZEeuOLcAiuBiIdw" tag="DB IdentifierQuoteString" value="`"/>
    <parameters xmi:id="_OzIG_HNZEeuOLcAiuBiIdw" key="CONN_PARA_KEY_USERNAME" value="root"/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.objectmodel.core:Dependency xmi:id="_OzIG_XNZEeuOLcAiuBiIdw" kind="Usage" supplier="_OzIG8HNZEeuOLcAiuBiIdw"/>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_OzIG_nNZEeuOLcAiuBiIdw" name="lotus" dataManager="_OzIG8HNZEeuOLcAiuBiIdw"/>
</xmi:XMI>
