<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_XP_IoNMLEeufxuhZN3u5oA" name="RedshiftEc2" id="_qtLTYNMGEeufxuhZN3u5oA" label="RedshiftEc2" dataPackage="_XP_Iq9MLEeufxuhZN3u5oA" DatabaseType="Redshift" DriverClass="com.amazon.redshift.jdbc42.Driver" URL="jdbc:redshift://redshift-cluster-1.cukumt9ua0or.us-east-2.redshift.amazonaws.com:5439/dev?" Port="5439" Username="awsuser" Password="enc:system.encryption.key.v1:3FHEmc621EJokxkGsQGU2Nr2IMhv/IvM41qjHgrYyjI1LQhUy0T2jwT9rw==" ServerName="redshift-cluster-1.cukumt9ua0or.us-east-2.redshift.amazonaws.com" DatasourceName="" FileFieldName="" SID="dev" SqlSynthax="" StringQuote="" NullChar="" DbmsId="redshift_id" ProductId="REDSHIFT" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="public">
    <taggedValue xmi:id="_XP_IodMLEeufxuhZN3u5oA" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_XP_IotMLEeufxuhZN3u5oA" tag="package filter" value=""/>
    <taggedValue xmi:id="_XP_Io9MLEeufxuhZN3u5oA" tag="Status" value=""/>
    <taggedValue xmi:id="_XP_IpNMLEeufxuhZN3u5oA" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_XP_IpdMLEeufxuhZN3u5oA" tag="Purpose" value=""/>
    <taggedValue xmi:id="_XP_IptMLEeufxuhZN3u5oA" tag="Description" value=""/>
    <taggedValue xmi:id="_XP_Ip9MLEeufxuhZN3u5oA" tag="Author" value=""/>
    <taggedValue xmi:id="_XP_IqNMLEeufxuhZN3u5oA" tag="otherParameter"/>
    <parameters xmi:id="_XP_IqdMLEeufxuhZN3u5oA" key="CONN_PARA_KEY_USERNAME" value="awsuser"/>
    <parameters xmi:id="_XP_IqtMLEeufxuhZN3u5oA" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_XP_Iq9MLEeufxuhZN3u5oA" name="dev" dataManager="_XP_IoNMLEeufxuhZN3u5oA">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_XP_IrNMLEeufxuhZN3u5oA" name="public"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
