<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_UhHRoFo4EeuDy6Zzx8NveA" name="LocalMSSQL_Talend001" id="_PV1fkFo4EeuDy6Zzx8NveA" label="LocalMSSQL_Talend001" dataPackage="_UhH4tFo4EeuDy6Zzx8NveA" DatabaseType="Microsoft SQL Server" DriverClass="com.microsoft.sqlserver.jdbc.SQLServerDriver" URL="jdbc:sqlserver://localhost:1434;DatabaseName=Talend_001;" dbVersionString="MSSQL_PROP" Port="1434" Username="sa" Password="enc:system.encryption.key.v1:df1KnPAswSGNE17a9hgA5BYhK0tqgENA9Ta4RkBvlPE2In8=" ServerName="localhost" DatasourceName="" FileFieldName="" SID="Talend_001" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_UhHRoVo4EeuDy6Zzx8NveA" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_UhHRolo4EeuDy6Zzx8NveA" tag="package filter" value=""/>
    <taggedValue xmi:id="_UhHRo1o4EeuDy6Zzx8NveA" tag="Status" value=""/>
    <taggedValue xmi:id="_UhHRpFo4EeuDy6Zzx8NveA" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_UhHRpVo4EeuDy6Zzx8NveA" tag="Purpose" value=""/>
    <taggedValue xmi:id="_UhHRplo4EeuDy6Zzx8NveA" tag="Description" value=""/>
    <taggedValue xmi:id="_UhHRp1o4EeuDy6Zzx8NveA" tag="Author" value=""/>
    <taggedValue xmi:id="_UhHRqFo4EeuDy6Zzx8NveA" tag="otherParameter"/>
    <taggedValue xmi:id="_UhHRqVo4EeuDy6Zzx8NveA" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_UhH4sFo4EeuDy6Zzx8NveA" tag="DB ProductVersion" value="15.00.2000"/>
    <taggedValue xmi:id="_UhH4sVo4EeuDy6Zzx8NveA" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_UhH4slo4EeuDy6Zzx8NveA" key="CONN_PARA_KEY_USERNAME" value="sa"/>
    <parameters xmi:id="_UhH4s1o4EeuDy6Zzx8NveA" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_UhH4tFo4EeuDy6Zzx8NveA" name="Talend_001" dataManager="_UhHRoFo4EeuDy6Zzx8NveA">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4tVo4EeuDy6Zzx8NveA" name="db_accessadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4tlo4EeuDy6Zzx8NveA" name="db_backupoperator"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4t1o4EeuDy6Zzx8NveA" name="db_datareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4uFo4EeuDy6Zzx8NveA" name="db_datawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4uVo4EeuDy6Zzx8NveA" name="db_ddladmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4ulo4EeuDy6Zzx8NveA" name="db_denydatareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4u1o4EeuDy6Zzx8NveA" name="db_denydatawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4vFo4EeuDy6Zzx8NveA" name="db_owner"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4vVo4EeuDy6Zzx8NveA" name="db_securityadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4vlo4EeuDy6Zzx8NveA" name="dbo"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4v1o4EeuDy6Zzx8NveA" name="guest"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4wFo4EeuDy6Zzx8NveA" name="INFORMATION_SCHEMA"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_UhH4wVo4EeuDy6Zzx8NveA" name="sys"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
